export * as facebook from './facebook'
export * as instagram from './instagram'
export * as amazon from './amazon'
export * as ebay from './ebay'
export * as linkedin from './linkedin'
export * as github from './github'
export * as schufa from './schufa'
export * as apple from './apple'